language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
install: pip install .
script: py.test

notifications:
  email:
    recipients:
      - egafni@gmail.com
      - yassinesouilmi@gmail.com
    on_success: never
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


  # Gitter notifications
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/69b116e4116196985f1b
      - https://webhooks.gitter.im/e/d633832f63a4e7c2ad7f

    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

  slack:

    rooms:
      - biostandards:sWYxFbqTh8MdyTeZkC7ZisgN#travis-ci
      - genomekey:Z5VoMKtrbyGNdWXW9Ovf06d4#travis-ci

    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
